apiVersion: 0.3.0
environments:
  default:
    destination:
      namespace: kubeflow
      server: https://localhost:6443
    k8sVersion: v1.10.3
    path: default
kind: ksonnet.io/app
name: ks_app
registries:
  incubator:
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
version: 0.0.1
